"""delete unused field in club member account

Revision ID: 03a5a5c8449a
Revises: 1f942053ac37
Create Date: 2021-08-11 21:59:52.867178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a5a5c8449a'
down_revision = '1f942053ac37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_user', sa.Column('fio', sa.String(length=256), nullable=True))
    op.drop_constraint('club_user_username_key', 'club_user', type_='unique')
    op.drop_column('club_user', 'firstname')
    op.drop_column('club_user', 'lastname')
    op.drop_column('club_user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_user', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('club_user', sa.Column('lastname', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('club_user', sa.Column('firstname', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('club_user_username_key', 'club_user', ['username'])
    op.drop_column('club_user', 'fio')
    # ### end Alembic commands ###
