"""Add relation between verified by and real user

Revision ID: 10be527715f7
Revises: e6988b011179
Create Date: 2021-09-18 13:44:43.532778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10be527715f7'
down_revision = 'e6988b011179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verified_user_by_club', sa.Column('verified_by_club_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'verified_user_by_club', 'club_user', ['verified_by_club_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verified_user_by_club', type_='foreignkey')
    op.drop_column('verified_user_by_club', 'verified_by_club_user_id')
    # ### end Alembic commands ###
