"""add owners to clubs

Revision ID: 1f942053ac37
Revises: f1fc7cf29947
Create Date: 2021-08-11 21:55:05.545256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f942053ac37'
down_revision = 'f1fc7cf29947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_user_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_user_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['club_user_id'], ['club_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('club', sa.Column('owner_club_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'club', 'club_user', ['owner_club_user_id'], ['id'])
    op.drop_constraint('club_user_club_id_fkey', 'club_user', type_='foreignkey')
    op.drop_column('club_user', 'club_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_user', sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('club_user_club_id_fkey', 'club_user', 'club', ['club_id'], ['id'])
    op.drop_constraint(None, 'club', type_='foreignkey')
    op.drop_column('club', 'owner_club_user_id')
    op.drop_table('club_user_association')
    # ### end Alembic commands ###
