"""Add club_work_schedules

Revision ID: 31483523f778
Revises: 6f36b123f2b2
Create Date: 2021-07-24 22:03:21.581811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31483523f778'
down_revision = '6f36b123f2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='days'), nullable=False),
    sa.Column('work_hours', sa.String(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_work_schedules')
    # ### end Alembic commands ###
