"""Added updated at field into public pages

Revision ID: 349f22b969ba
Revises: 908138c99437
Create Date: 2021-08-11 20:23:35.820806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349f22b969ba'
down_revision = '908138c99437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'updated_at')
    # ### end Alembic commands ###
