"""Added updated_at to order

Revision ID: 3be18d944c9e
Revises: 8f0ca36884fe
Create Date: 2021-08-07 18:37:16.633064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be18d944c9e'
down_revision = '8f0ca36884fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'updated_at')
    # ### end Alembic commands ###
