"""Add owner user

Revision ID: 6e2a96e677df
Revises: 0a780422d310
Create Date: 2021-09-05 11:58:17.631002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2a96e677df'
down_revision = '0a780422d310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_user', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'club_user', 'club_user', ['owner_user_id'], ['id'])
    op.add_column('notification', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'created_at')
    op.drop_constraint(None, 'club_user', type_='foreignkey')
    op.drop_column('club_user', 'owner_user_id')
    # ### end Alembic commands ###
