"""Add callbacks for invoices

Revision ID: 8309b5350816
Revises: 56c7ee274fe9
Create Date: 2021-09-26 14:53:15.930360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8309b5350816'
down_revision = '56c7ee274fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices_callbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sha1_hash', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices_callbacks')
    # ### end Alembic commands ###
