"""Add callbacks for invoices

Revision ID: 8ba459f0cbea
Revises: 8309b5350816
Create Date: 2021-09-26 15:04:27.728528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ba459f0cbea'
down_revision = '8309b5350816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices_callbacks', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices_callbacks', 'invoice', ['invoice_id'], ['id'])
    op.drop_column('invoices_callbacks', 'invoice_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices_callbacks', sa.Column('invoice_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices_callbacks', type_='foreignkey')
    op.drop_column('invoices_callbacks', 'invoice_id')
    # ### end Alembic commands ###
