"""Add completed field to order

Revision ID: 92434868b996
Revises: bf7d8a3cced8
Create Date: 2021-08-08 17:31:14.578362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92434868b996'
down_revision = 'bf7d8a3cced8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('complete', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'complete')
    # ### end Alembic commands ###
