"""Add completed at time

Revision ID: 977e8cddbe40
Revises: 92434868b996
Create Date: 2021-08-08 18:11:34.515704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977e8cddbe40'
down_revision = '92434868b996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'completed_at')
    # ### end Alembic commands ###
