"""Add confirmed at time

Revision ID: b57e8459f231
Revises: 977e8cddbe40
Create Date: 2021-08-08 18:14:37.389656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57e8459f231'
down_revision = '977e8cddbe40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'confirmed_at')
    # ### end Alembic commands ###
