"""Fix amount in user balance

Revision ID: bd21a4957acd
Revises: c3db51e38988
Create Date: 2021-09-28 21:12:33.721347

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bd21a4957acd'
down_revision = 'c3db51e38988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute("""ALTER TABLE "invoice" ALTER COLUMN "amount" TYPE DOUBLE PRECISION;""")
    op.get_bind().execute("""ALTER TABLE "invoice" ALTER COLUMN "amount" SET NOT NULL;""")
    op.get_bind().execute("""ALTER TABLE "invoice" ALTER COLUMN "amount" DROP DEFAULT;""")
    op.get_bind().execute("""ALTER TABLE "user_balance" ALTER COLUMN "amount" TYPE DOUBLE PRECISION;""")
    op.get_bind().execute("""ALTER TABLE "user_balance" ALTER COLUMN "amount" SET NOT NULL;""")
    op.get_bind().execute("""ALTER TABLE "user_balance" ALTER COLUMN "amount" DROP DEFAULT;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
