"""Update order

Revision ID: e4dc0777f7b8
Revises: b57e8459f231
Create Date: 2021-08-08 21:05:55.618053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4dc0777f7b8'
down_revision = 'b57e8459f231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('client_arrived_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('club_confirmed_client_arrived_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('client_completed_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('club_confirmed_client_completed_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('client_canceled_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('club_canceled_at', sa.DateTime(), nullable=True))
    op.alter_column('order', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('order', 'confirmed_club')
    op.drop_column('order', 'confirmed_at')
    op.drop_column('order', 'canceled_by_client')
    op.drop_column('order', 'completed_at')
    op.drop_column('order', 'is_active')
    op.drop_column('order', 'confirmed_client')
    op.drop_column('order', 'canceled_by_club')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('canceled_by_club', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('confirmed_client', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('canceled_by_client', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('confirmed_club', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('order', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('order', 'club_canceled_at')
    op.drop_column('order', 'client_canceled_at')
    op.drop_column('order', 'club_confirmed_client_completed_at')
    op.drop_column('order', 'client_completed_at')
    op.drop_column('order', 'club_confirmed_client_arrived_at')
    op.drop_column('order', 'client_arrived_at')
    # ### end Alembic commands ###
