"""Add verified info

Revision ID: e6988b011179
Revises: 6e2a96e677df
Create Date: 2021-09-12 17:03:31.045659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6988b011179'
down_revision = '6e2a96e677df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verified_user_by_club', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verified_user_by_club', 'complete')
    # ### end Alembic commands ###
