"""Add default club_uuid

Revision ID: f163b2eea97d
Revises: bd21a4957acd
Create Date: 2021-10-01 21:58:29.938809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f163b2eea97d'
down_revision = 'bd21a4957acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute("""
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    """)
    op.add_column('club', sa.Column('club_uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'club_uuid')
    op.get_bind().execute("""
        DROP EXTENSION IF EXISTS "uuid-ossp";
    """)
    # ### end Alembic commands ###
