"""Update club user

Revision ID: f1fc7cf29947
Revises: 349f22b969ba
Create Date: 2021-08-11 21:37:44.737000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fc7cf29947'
down_revision = '349f22b969ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_user', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('club_user', 'firstname',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('club_user', 'lastname',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('club_user', 'date_of_birth')
    op.drop_column('club_user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_user', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('club_user', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('club_user', 'lastname',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('club_user', 'firstname',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('club_user', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
