"""Add geometry field

Revision ID: f3ba2eceef32
Revises: af92926e65ea
Create Date: 2021-06-18 19:47:59.530180

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'f3ba2eceef32'
down_revision = 'af92926e65ea'
branch_labels = None
depends_on = None


def upgrade():
    op.get_bind().execute("""CREATE EXTENSION IF NOT EXISTS postgis;""")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'point')
    op.get_bind().execute("""DROP EXTENSION IF EXISTS postgis CASCADE;""")
    # ### end Alembic commands ###
